-- MySQL Script generated by MySQL Workbench
-- Wed Jun  6 16:21:57 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema database-qllk
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema database-qllk
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `database-qllk` DEFAULT CHARACTER SET utf8 ;
USE `database-qllk` ;

-- -----------------------------------------------------
-- Table `database-qllk`.`LOAIMATHANG`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `database-qllk`.`LOAIMATHANG` (
  `MaLoai` VARCHAR(10) NOT NULL,
  `TenLoai` NVARCHAR(45) NOT NULL,
  PRIMARY KEY (`MaLoai`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `database-qllk`.`KHO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `database-qllk`.`KHO` (
  `MaKhu` VARCHAR(4) NOT NULL,
  `TenKhu` NVARCHAR(45) NULL,
  PRIMARY KEY (`MaKhu`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `database-qllk`.`DONVITINH`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `database-qllk`.`DONVITINH` (
  `MaDV` VARCHAR(10) NOT NULL,
  `TenDV` NVARCHAR(45) NULL,
  PRIMARY KEY (`MaDV`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `database-qllk`.`MATHANG`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `database-qllk`.`MATHANG` (
  `MaMH` VARCHAR(10) NOT NULL,
  `TenMH` NVARCHAR(45) NOT NULL,
  `HangSX` NVARCHAR(45) NULL,
  `MaDV` VARCHAR(10) NULL,
  `CauHinh` NVARCHAR(100) NULL,
  `MaLoai` VARCHAR(10) NULL,
  `MaKhu` VARCHAR(4) NULL,
  `SoLuong` INT NULL,
  PRIMARY KEY (`MaMH`),
  INDEX `MaLoai_idx` (`MaLoai` ASC),
  INDEX `MaKhu_idx` (`MaKhu` ASC),
  INDEX `MaDV_idx` (`MaDV` ASC),
  CONSTRAINT `fk_MATHANG_LOAIMATHANG`
    FOREIGN KEY (`MaLoai`)
    REFERENCES `database-qllk`.`LOAIMATHANG` (`MaLoai`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_MATHANG_KHO`
    FOREIGN KEY (`MaKhu`)
    REFERENCES `database-qllk`.`KHO` (`MaKhu`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_MATHANG_DONVITINH`
    FOREIGN KEY (`MaDV`)
    REFERENCES `database-qllk`.`DONVITINH` (`MaDV`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `database-qllk`.`PHONGBAN`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `database-qllk`.`PHONGBAN` (
  `MaPhong` VARCHAR(10) NOT NULL,
  `TenPhong` NVARCHAR(45) NOT NULL,
  PRIMARY KEY (`MaPhong`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `database-qllk`.`NHANVIEN`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `database-qllk`.`NHANVIEN` (
  `MaNV` VARCHAR(10) NOT NULL,
  `TenNV` NVARCHAR(45) NOT NULL,
  `Phai` NVARCHAR(4) NULL,
  `MaPhong` VARCHAR(10) NULL,
  PRIMARY KEY (`MaNV`),
  INDEX `MaPhong_idx` (`MaPhong` ASC),
  CONSTRAINT `fk_NHANVIEN_PHONGBAN`
    FOREIGN KEY (`MaPhong`)
    REFERENCES `database-qllk`.`PHONGBAN` (`MaPhong`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `database-qllk`.`KHACHHANG`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `database-qllk`.`KHACHHANG` (
  `MaKH` VARCHAR(10) NOT NULL,
  `TenKH` NVARCHAR(45) NOT NULL,
  `DiaChi` NVARCHAR(60) NULL,
  `Email` VARCHAR(40) NULL,
  `SoDT` VARCHAR(15) NOT NULL,
  PRIMARY KEY (`MaKH`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `database-qllk`.`HOADON`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `database-qllk`.`HOADON` (
  `MaHD` VARCHAR(10) NOT NULL,
  `NgayLap` DATETIME NULL,
  `MaSoThue` VARCHAR(45) NULL,
  `TongTien` INT NULL,
  `MaNV` VARCHAR(10) NULL,
  `MaKH` VARCHAR(10) NULL,  
  PRIMARY KEY (`MaHD`),
  INDEX `MaNV_idx` (`MaNV` ASC),
  INDEX `MaKH_idx` (`MaKH` ASC),
  CONSTRAINT `fk_HOADON_PNHANVIEN`
    FOREIGN KEY (`MaNV`)
    REFERENCES `database-qllk`.`NHANVIEN` (`MaNV`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_HOADON_KHACHHANG`
    FOREIGN KEY (`MaKH`)
    REFERENCES `database-qllk`.`KHACHHANG` (`MaKH`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `database-qllk`.`CHITIETHOADON`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `database-qllk`.`CHITIETHOADON` (
  `MaCTHD` VARCHAR(10) NOT NULL,
  `DonGiaBan` INT NOT NULL,
  `SoLuong` INT NULL,
  `MaHD` VARCHAR(10) NULL,
  `MaMH` VARCHAR(10) NULL,
  `TienThanhToan` INT NOT NULL,
  PRIMARY KEY (`MaCTHD`),
  INDEX `MaHD_idx` (`MaHD` ASC),
  INDEX `MaMH_idx` (`MaMH` ASC),
  CONSTRAINT `fk_CHITIETHOADON_HOADON`
    FOREIGN KEY (`MaHD`)
    REFERENCES `database-qllk`.`HOADON` (`MaHD`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_CHITIETHOADON_MATHANG`
    FOREIGN KEY (`MaMH`)
    REFERENCES `database-qllk`.`MATHANG` (`MaMH`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `database-qllk`.`NHACUNGCAP`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `database-qllk`.`NHACUNGCAP` (
  `MaNCC` VARCHAR(10) NOT NULL,
  `TenNCC` NVARCHAR(50) NULL,
  `DiaChiNCC` NVARCHAR(50) NULL,
  `EmailNCC` VARCHAR(40) NULL,
  `SoDTNCC` VARCHAR(15) NULL,
  PRIMARY KEY (`MaNCC`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `database-qllk`.`DONDATHANG`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `database-qllk`.`DONDATHANG` (
  `MaDDH` VARCHAR(10) NOT NULL,
  `NgayLap` DATETIME NULL,
  `MaNV` VARCHAR(10) NULL,
  `MaNCC` VARCHAR(10) NULL,
  PRIMARY KEY (`MaDDH`),
  INDEX `MaNV_idx` (`MaNV` ASC),
  INDEX `MaNCC_idx` (`MaNCC` ASC),
  CONSTRAINT `fk_DONDATHANG_NHANVIEN`
    FOREIGN KEY (`MaNV`)
    REFERENCES `database-qllk`.`NHANVIEN` (`MaNV`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_DONDATHANG_NHACUNGCAP`
    FOREIGN KEY (`MaNCC`)
    REFERENCES `database-qllk`.`NHACUNGCAP` (`MaNCC`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `database-qllk`.`CHITIETDONDATHANG`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `database-qllk`.`CHITIETDONDATHANG` (
  `MaCTDDH` VARCHAR(10) NOT NULL,
  `SoLuong` INT NULL,
  `MaDDH` VARCHAR(10) NULL,
  `MaMH` VARCHAR(10) NULL,
  PRIMARY KEY (`MaCTDDH`),
  INDEX `MaDDH_idx` (`MaDDH` ASC),
  INDEX `MaMH_idx` (`MaMH` ASC),
  CONSTRAINT `fk_CHITIETDONDATHANG_DONDATHANG`
    FOREIGN KEY (`MaDDH`)
    REFERENCES `database-qllk`.`DONDATHANG` (`MaDDH`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_CHITIETDONDATHANG_MATHANG`
    FOREIGN KEY (`MaMH`)
    REFERENCES `database-qllk`.`MATHANG` (`MaMH`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `database-qllk`.`PHANQUYEN`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `database-qllk`.`PHANQUYEN` (
  `MaPQ` VARCHAR(10) NOT NULL,
  `TenPQ` NVARCHAR(45) NULL,
  PRIMARY KEY (`MaPQ`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `database-qllk`.`DANGNHAP`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `database-qllk`.`DANGNHAP` (
  `MaDN` VARCHAR(10) NOT NULL,
  `TenHienThi` NVARCHAR(30) NULL,
  `Username` VARCHAR(100) NULL,
  `Password` VARCHAR(20) NULL,
  `MaPQ` VARCHAR(10) NULL,
  PRIMARY KEY (`MaDN`),
  INDEX `Username_idx` (`Username` ASC),
  INDEX `MaPQ_idx` (`MaPQ` ASC),
  CONSTRAINT `fk_DANGNHAP_PHANQUYEN`
    FOREIGN KEY (`MaPQ`)
    REFERENCES `database-qllk`.`PHANQUYEN` (`MaPQ`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_DANGNHAP_NHANVIEN`
    FOREIGN KEY (`Username`)
    REFERENCES `database-qllk`.`NHANVIEN` (`MaNV`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `database-qllk`.`PHIEUNHAPHANG`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `database-qllk`.`PHIEUNHAPHANG` (
  `MaPN` VARCHAR(10) NOT NULL,
  `NgayLapPhieu` DATETIME NULL,
  `MaNV` VARCHAR(10) NULL,
  `TongTienPN` INT NULL,
  `MaDDH` VARCHAR(10) NULL,
  PRIMARY KEY (`MaPN`),
  INDEX `MaNV_idx` (`MaNV` ASC),
  INDEX `MaDDH_idx` (`MaDDH` ASC),
  CONSTRAINT `fk_PHIEUNHAPHANG_NHANVIEN`
    FOREIGN KEY (`MaNV`)
    REFERENCES `database-qllk`.`NHANVIEN` (`MaNV`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_PHIEUNHAPHANG_DONDATHANG`
    FOREIGN KEY (`MaDDH`)
    REFERENCES `database-qllk`.`DONDATHANG` (`MaDDH`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `database-qllk`.`CHITIETPHIEUNHAP`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `database-qllk`.`CHITIETPHIEUNHAP` (
  `MaCTPN` VARCHAR(10) NOT NULL,
  `SoLuong` INT NULL,
  `DonGia` VARCHAR(45) NULL,
  `DonGiaBan` VARCHAR(45) NULL,
  `GhiChu` VARCHAR(45) NULL,
  `MaPN` VARCHAR(10) NULL,
  `TongTien` INT NULL,
  `MaMH` VARCHAR(10) NULL,
  PRIMARY KEY (`MaCTPN`),
  INDEX `MaPN_idx` (`MaPN` ASC),
  INDEX `MaMH_idx` (`MaMH` ASC),
  CONSTRAINT `fk_CHITIETPHIEUNHAP_PHIEUNHAPHANG`
    FOREIGN KEY (`MaPN`)
    REFERENCES `database-qllk`.`PHIEUNHAPHANG` (`MaPN`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_CHITIETPHIEUNHAP_MATHANG`
    FOREIGN KEY (`MaMH`)
    REFERENCES `database-qllk`.`MATHANG` (`MaMH`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `database-qllk`.`BAOCAOHANGTON`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `database-qllk`.`BAOCAOHANGTON` (
  `MaBCHT` VARCHAR(10) NOT NULL,
  `NgayLap` DATETIME NULL,
  `Thang` INT NULL,
  `TongNhap` INT NULL,
  `TongTon` INT NULL,
  `TongBan` INT NULL,
  `MaNV` VARCHAR(10) NULL,
  PRIMARY KEY (`MaBCHT`),
  INDEX `MaNV_idx` (`MaNV` ASC),
  CONSTRAINT `fk_BAOCAOHANGTON_NHANVIEN`
    FOREIGN KEY (`MaNV`)
    REFERENCES `database-qllk`.`NHANVIEN` (`MaNV`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `database-qllk`.`BAOCAOTHUCHI`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `database-qllk`.`BAOCAOTHUCHI` (
  `MaBCTC` VARCHAR(10) NOT NULL,
  `NgayLap` DATETIME NULL,
  `TongThu` INT NULL,
  `TongChi` INT NULL,
  `MaNV` VARCHAR(10) NULL,
  `TuyChon` VARCHAR(45) NULL,
  `ThoiGian` VARCHAR(8) NULL,
  PRIMARY KEY (`MaBCTC`),
  INDEX `MaNV_idx` (`MaNV` ASC),
  CONSTRAINT `fk_BAOCAOTHUCHI_NHANVIEN`
    FOREIGN KEY (`MaNV`)
    REFERENCES `database-qllk`.`NHANVIEN` (`MaNV`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `database-qllk`.`CHITIETBAOCAOHANGTON`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `database-qllk`.`CHITIETBAOCAOHANGTON` (
  `MaCTBC` VARCHAR(10) NOT NULL,
  `LuongNhapBĐ` INT NULL,
  `LuongBan` INT NULL,
  `LuongTon` INT NULL,
  `MaMH` VARCHAR(10) NULL,
  `MaBCHT` VARCHAR(10) NULL,
  PRIMARY KEY (`MaCTBC`),
  INDEX `MaMH_idx` (`MaMH` ASC),
  INDEX `MaBCHT_idx` (`MaBCHT` ASC),
  CONSTRAINT `fk_CHITIETBAOCAOHANGTON_MATHANG`
    FOREIGN KEY (`MaMH`)
    REFERENCES `database-qllk`.`MATHANG` (`MaMH`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_CHITIETBAOCAOHANGTON_BAOCAOHANGTON`
    FOREIGN KEY (`MaBCHT`)
    REFERENCES `database-qllk`.`BAOCAOHANGTON` (`MaBCHT`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `database-qllk`.`CHITIETTHU`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `database-qllk`.`CHITIETTHU` (
  `MaCTT` VARCHAR(10) NOT NULL,
  `MaBCTC` VARCHAR(10) NULL,
  `MaMH` VARCHAR(10) NULL,
  `TongBan` INT NULL,
  PRIMARY KEY (`MaCTT`),
  INDEX `MaBCTC_idx` (`MaBCTC` ASC),
  INDEX `MaMH_idx` (`MaMH` ASC),
  CONSTRAINT `fk_CHITIETTHU_BAOCAOTHUCHI`
    FOREIGN KEY (`MaBCTC`)
    REFERENCES `database-qllk`.`BAOCAOTHUCHI` (`MaBCTC`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_CHITIETTHU_CHITIETHOADON`
    FOREIGN KEY (`MaMH`)
    REFERENCES `database-qllk`.`CHITIETHOADON` (`MaMH`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `database-qllk`.`CHITIETCHI`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `database-qllk`.`CHITIETCHI` (
  `MaCTC` VARCHAR(10) NOT NULL,
  `MaBCTC` VARCHAR(10) NULL,
  `MaMH` VARCHAR(10) NULL,
  `TongNhap` INT NULL,
  PRIMARY KEY (`MaCTC`),
  INDEX `MaBCTC_idx` (`MaBCTC` ASC),
  INDEX `MaMH_idx` (`MaMH` ASC),
  CONSTRAINT `fk_CHITIETCHI_BAOCAOTHUCHI`
    FOREIGN KEY (`MaBCTC`)
    REFERENCES `database-qllk`.`BAOCAOTHUCHI` (`MaBCTC`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_CHITIETCHI_CHITIETPHIEUNHAP`
    FOREIGN KEY (`MaMH`)
    REFERENCES `database-qllk`.`CHITIETPHIEUNHAP` (`MaMH`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

SELECT * FROM `database-qllk`.khachhang;
insert into `database-qllk`.khachhang values ('KH001', N'Đặng Hoàng Long', N'123 Đường ABC', N'long97@gmail.com', '0123456789');
insert into `database-qllk`.khachhang values ('KH002', N'Phạm Nhật Phi', N'3 Đường số 2', N'phipn@gmail.com', '0903123456');

SELECT * FROM `database-qllk`.phongban;
insert into `database-qllk`.PHONGBAN values ('PB001', N'Bộ phận kế toán');
insert into `database-qllk`.PHONGBAN values ('PB002', N'Bộ phận kinh doanh');
insert into `database-qllk`.PHONGBAN values ('PB003', N'Bộ phận thủ kho');
INSERT INTO `database-qllk`.PHONGBAN VALUES ('PB004', N'Ban Giám đốc');

SELECT * FROM `database-qllk`.nhanvien;
insert into `database-qllk`.NHANVIEN values ('NV002', N'Trần Văn A', N'Nam', 'PB001');
insert into `database-qllk`.NHANVIEN values ('NV001', N'Phạm Thị Minh', N'Nữ', 'PB002');
insert into `database-qllk`.NHANVIEN values ('NV003', N'Đặng Văn Thành', N'Nam', 'PB004');
insert into `database-qllk`.NHANVIEN values ('NV004', N'Nguyễn Thị Trang', N'Nữ', 'PB003');

SELECT * FROM `database-qllk`.NHACUNGCAP;
DELETE FROM `database-qllk`.NHACUNGCAP WHERE MaNCC = 'NCC06';
INSERT INTO `database-qllk`.NHACUNGCAP VALUES('NCC001', N'Công Ty TNHH Tin học Đông Phúc', N'147 ĐƯỜNG BA CU', 'DONGPHUC@GMAIL.COM', '0978456812');
INSERT INTO `database-qllk`.NHACUNGCAP VALUES('NCC002', N'Công Ty TNHH Nam Thông Bảo', N'258 ĐƯỜNG LÊ DUẨN', 'NAMTHONGBAO@GMAIL.COM', '0903456200');
INSERT INTO `database-qllk`.NHACUNGCAP VALUES('NCC003', N'Công Ty TNHH TM DV Tin Học Hoàng Khang', N'369 ĐƯỜNG HOA SỮA', 'HOANGKHANG@GMAIL.COM', '09039994533');
INSERT INTO `database-qllk`.NHACUNGCAP VALUES('NCC004', N'Công Ty TNHH TM & DV Nhật Tân Tín', N'357 ĐƯỜNG VÕ THỊ SÁU', 'NHATTANTIN@GMAIL.COM', '01228041103');
INSERT INTO `database-qllk`.NHACUNGCAP VALUES('NCC005', N'Công Ty TNHH MTV Tên Lửa Số', N'159 ĐƯỜNG ĐINH TIÊN HOÀNG', 'TENLUASO@GMAIL.COM', '01227456666');
INSERT INTO `database-qllk`.NHACUNGCAP VALUES('NCC006', N'Công Ty TNHH Vi Tính Tiến Phát', N'123 ĐƯỜNG LÊ VĂN SỈ', 'TIENPHAT@GMAIL.COM', '01697542311');

SELECT * FROM `database-qllk`.PHANQUYEN;
insert into `database-qllk`.PHANQUYEN values ('PQ001', N'Admin');
insert into `database-qllk`.PHANQUYEN values ('PQ002', N'Kế Toán');
insert into `database-qllk`.PHANQUYEN values ('PQ003', N'Kinh doanh');
insert into `database-qllk`.PHANQUYEN values ('PQ004', N'Thủ kho');


SELECT * FROM `database-qllk`.DANGNHAP;
INSERT INTO `database-qllk`.DANGNHAP VALUES ('DN001', N'Bộ phận kế toán', 'NV002', '123', 'PQ002');
INSERT INTO `database-qllk`.DANGNHAP VALUES ('DN002', N'Bộ phận kinh doanh', 'NV001', '456', 'PQ003');
INSERT INTO `database-qllk`.DANGNHAP VALUES ('DN003', N'Bộ phận thủ kho', 'NV004', 'ABC', 'PQ004');
INSERT INTO `database-qllk`.DANGNHAP VALUES ('DN004', N'ADMIN Giám đốc', 'NV003', 'xyz', 'PQ001');

SELECT * FROM `database-qllk`.DONVITINH;
INSERT INTO `database-qllk`.DONVITINH VALUES ('DV001', N'CÁI');
INSERT INTO `database-qllk`.DONVITINH VALUES ('DV002', N'CÂY');
INSERT INTO `database-qllk`.DONVITINH VALUES ('DV003', N'BỘ');

SELECT * FROM `database-qllk`.KHO;
INSERT INTO `database-qllk`.KHO VALUES ('K001', N'A');
INSERT INTO `database-qllk`.KHO VALUES ('K002', N'B');
INSERT INTO `database-qllk`.KHO VALUES ('K003', N'C');

SELECT * FROM `database-qllk`.LOAIMATHANG;
INSERT INTO `database-qllk`.LOAIMATHANG VALUES ('LMH001', N'RAM MÁY TÍNH');
INSERT INTO `database-qllk`.LOAIMATHANG VALUES ('LMH002', N'CARD ĐỒ HỌA');
INSERT INTO `database-qllk`.LOAIMATHANG VALUES ('LMH003', N'MÀN HÌNH MÁY TÍNH');
INSERT INTO `database-qllk`.LOAIMATHANG VALUES ('LMH004', N'BÀN PHÍM MÁY TÍNH');

SELECT * FROM `database-qllk`.MATHANG; 
INSERT INTO `database-qllk`.MATHANG VALUES ('MH001', N'KEYBOARD', N'LOGITECH', 'DV001', 'KEYBOARD MÀU ĐEN CƠ NẶNG 30g', 'LMH004', 'K002', '20');
INSERT INTO `database-qllk`.MATHANG VALUES ('MH002', N'KEYBOARD APPLE', N'APPLE', 'DV001', 'KEYBOARD MÀU TRẮNG', 'LMH004', 'K002', '15');
INSERT INTO `database-qllk`.MATHANG VALUES ('MH003', N'RAM 2016', N'INTEL', 'DV002', 'RAM 32GB', 'LMH001', 'K001', '25');

SELECT * FROM `database-qllk`.BAOCAOHANGTON;

SELECT * FROM `database-qllk`.CHITIETBAOCAOHANGTON;
INSERT INTO `database-qllk`.CHITIETBAOCAOHANGTON VALUES ('CTBC002', '40', '10', '30', 'MH004','BCHT001');
INSERT INTO `database-qllk`.CHITIETBAOCAOHANGTON VALUES ('CTBC001', '60', '25', '35', 'MH002','BCHT001');
delete from `database-qllk`.BAOCAOHANGTON where MaBCHT = 'BCHT001';

SELECT BCHT.MaBCHT, BCHT.NgayLap, BCHT.Thang, NV.TenNV, SUM(CTBC.LuongNhapBĐ) AS TongNhap, SUM(CTBC.LuongBan) AS TongBan, SUM(CTBC.LuongTon) AS TongTon FROM BAOCAOHANGTON BCHT JOIN NHANVIEN NV ON BCHT.MaNV = NV.MaNV AND CTBC.MaBCHT = BCHT.MaBCHT;
INSERT INTO `database-qllk`.BAOCAOHANGTON VALUES ('BCHT001', '2018/06/11', '6', '0', '0', '0', 'NV002');
delete from `database-qllk`.CHITIETBAOCAOHANGTON where MaCTBC = 'CTBC001';
SELECT CTBCHT.MaCTBC, MH.TenMH, SUM(CTPN.SoLuong) AS LuongNhapBĐ, SUM(CTHD.SoLuong) AS LuongBan, SUM(MH.SoLuong) AS LuongTon 
FROM CHITIETBAOCAOHANGTON CTBCHT JOIN MATHANG MH JOIN CHITIETPHIEUNHAP CTPN JOIN CHITIETHOADON CTHD 
ON CTBCHT.MaMH = MH.MaMH AND CTPN.MaMH = CTBCHT.MaMH AND CTHD.MaMH = CTBCHT.MaMH 
WHERE MaBCHT = 'BCHT001' 
GROUP BY TenMH;
SELECT BCHT.MaBCHT, SUM(CTBC.LuongNhapBĐ) AS TongNhap, SUM(CTBC.LuongTon) AS TongTon, SUM(CTBC.LuongBan) AS TongBan FROM BAOCAOHANGTON BCHT JOIN CHITIETBAOCAOHANGTON CTBC ON CTBC.MaBCHT = BCHT.MaBCHT WHERE BCHT.MaBCHT = 'BCHT001';

SELECT MH.TenMH, MONTH(HD.NgayLap), SUM(CTPN.SoLuong) AS LuongNhapBĐ, SUM(CTHD.SoLuong) AS LuongBan, SUM(MH.SoLuong) AS LuongTon 
FROM CHITIETPHIEUNHAP CTPN, PHIEUNHAPHANG PN, HOADON HD, CHITIETHOADON CTHD, MATHANG MH 
WHERE CTPN.MaPN = PN.MaPN AND CTHD.MaHD = HD.MaHD AND CTHD.MaMH = MH.MaMH 
AND MONTH(PN.NgayLapPhieu) = '6' AND MONTH(HD.NgayLap) = '6' GROUP BY MH.TenMH;

SELECT * FROM `database-qllk`.BAOCAOTHUCHI;

SELECT * FROM `database-qllk`.DONDATHANG;
INSERT INTO `database-qllk`.DONDATHANG VALUES ('DDH001', '2018/05/30', 'NV002', 'NCC001');
INSERT INTO `database-qllk`.DONDATHANG VALUES ('DDH002', '2018/06/10', 'NV001', 'NCC005');
INSERT INTO `database-qllk`.DONDATHANG VALUES ('DDH003', '2018/05/25', 'NV002', 'NCC002');
INSERT INTO `database-qllk`.DONDATHANG VALUES ('DDH004', '2018/06/05', 'NV003', 'NCC003');

SELECT * FROM `database-qllk`.CHITIETDONDATHANG;
INSERT INTO `database-qllk`.CHITIETDONDATHANG VALUES ('CTDH001', '15', 'DDH001', 'MH002');
INSERT INTO `database-qllk`.CHITIETDONDATHANG VALUES ('CTDH002', '20', 'DDH001', 'MH001');
INSERT INTO `database-qllk`.CHITIETDONDATHANG VALUES ('CTDH003', '25', 'DDH002', 'MH003');

SELECT * FROM `database-qllk`.HOADON;
INSERT INTO `database-qllk`.HOADON VALUES ('HD001', '2018/06/10', '1223165161', '', 'NV002', 'KH001');
UPDATE `database-qllk`.HOADON SET TongTien = '825000' WHere MaHD = 'HD001'; 
SELECT HD.MaHD, HD.NgayLap, HD.MaSoThue, HD.TongTien, NV.TenNV, KH.TenKH FROM HOADON HD JOIN NHANVIEN NV JOIN KHACHHANG KH ON HD.MaNV = NV.MaNV AND HD.MaKH = KH.MaKH;
SELECT HD.MaHD, HD.NgayLap, HD.MaSoThue, HD.TongTien, NV.TenNV, KH.TenKH FROM HOADON HD JOIN NHANVIEN NV JOIN KHACHHANG KH JOIN CHITIETHOADON CTHD ON CTHD.MaHD = HD.MaHD AND HD.MaNV = NV.MaNV AND HD.MaKH = KH.MaKH;

SELECT * FROM `database-qllk`.CHITIETHOADON;
INSERT INTO `database-qllk`.CHITIETHOADON VALUES ('CTHD001', '165000', '5', 'HD001', 'MH004', '825000');
SELECT HD.MaHD, NgayLap, MaSoThue, SUM(NULLIF(CTHD.TienThanhToan, 1)) AS TongTien, NV.TenNV, KH.TenKH FROM HOADON HD JOIN NHANVIEN NV JOIN KHACHHANG KH JOIN CHITIETHOADON CTHD ON CTHD.MaHD = HD.MaHD AND HD.MaNV = NV.MaNV AND HD.MaKH = KH.MaKH;
SELECT HD.MaHD, NVL(SUM(CTHD.TienThanhToan),0) AS TongTien FROM HOADON HD LEFT JOIN CHITIETHOADON CTHD ON CTHD.MaHD = HD.MaHD;

SELECT * FROM `database-qllk`.PHIEUNHAPHANG;
INSERT INTO `database-qllk`.PHIEUNHAPHANG VALUES ('PN001', '2018/06/01', 'NV003', '37500000', 'DDH002');
INSERT INTO `database-qllk`.PHIEUNHAPHANG VALUES ('PN002', '2018/06/05', 'NV002', '7500000', 'DDH001');

SELECT * FROM `database-qllk`.CHITIETPHIEUNHAP;
INSERT INTO `database-qllk`.CHITIETPHIEUNHAP VALUES ('CTPN001', '20', '150000', '180000', N'ĐÃ NHẬP ĐỦ', 'PN001', '3000000', 'MH001');
INSERT INTO `database-qllk`.CHITIETPHIEUNHAP VALUES ('CTPN002', '15', '300000', '350000', N'ĐÃ NHẬP ĐỦ', 'PN001', '4500000', 'MH002');
INSERT INTO `database-qllk`.CHITIETPHIEUNHAP VALUES ('CTPN003', '25', '1500000', '1800000', N'ĐÃ NHẬP ĐỦ', 'PN001', '37500000', 'MH003');